apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hp2jnl79q-go
  janus-idp.io/tekton: hp2jnl79q-go
  backstage.io/kubernetes-id: hp2jnl79q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hp2jnl79q-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
