apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hp2jnl79q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hp2jnl79q-go 
  name: hp2jnl79q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hp2jnl79q-go 
